### ISSUE TITLE
http do not work at all

### ISSUE THREAD

**Issue by sanguohot** [facebookincubator/fbender#1]
This project seems interesting.
But it is not ready to use.
This is my simple test case: 
> root@sanguohot-baidu:~# go version
> go version go1.11 linux/amd64
> root@sanguohot-baidu:~# fbender http throughput fixed --target www.baidu.com --duration 1m --ssl 2000 4000 8000
> GET /
> 
> Warning: Error parsing input line "": input must have a format of 'GET RelativeURL' or 'POST RelativeURL FormData', got ''
> ^C
> root@sanguohot-baidu:~# cat queries.txt 
> GET /
> root@sanguohot-baidu:~# fbender http throughput fixed --target www.baidu.com --duration 1m --ssl 2000 4000 8000 --input queries.txt
> Cleaning up the memory... Done.
> fatal error: runtime: out of memory
> 
> runtime stack:
> runtime.throw(0x8dae76, 0x16)
>         /root/.gvm/gos/go1.11/src/runtime/panic.go:608 +0x72
> runtime.sysMap(0xc004000000, 0x3bc000000, 0xc8cfb8)
>         /root/.gvm/gos/go1.11/src/runtime/mem_linux.go:156 +0xc7
> runtime.(*mheap).sysAlloc(0xc73c60, 0x3bc000000, 0x7f603aeef738, 0x7f6037d13d60)
>         /root/.gvm/gos/go1.11/src/runtime/malloc.go:619 +0x1c7
> runtime.(*mheap).grow(0xc73c60, 0x1dcd66, 0x0)
>         /root/.gvm/gos/go1.11/src/runtime/mheap.go:920 +0x42
> runtime.(*mheap).allocSpanLocked(0xc73c60, 0x1dcd66, 0xc8cfc8, 0x7f603aeef6a0)
>         /root/.gvm/gos/go1.11/src/runtime/mheap.go:848 +0x337
> runtime.(*mheap).alloc_m(0xc73c60, 0x1dcd66, 0x410101, 0x7f6038520000)
>         /root/.gvm/gos/go1.11/src/runtime/mheap.go:692 +0x119
> runtime.(*mheap).alloc.func1()
>         /root/.gvm/gos/go1.11/src/runtime/mheap.go:759 +0x4c
> runtime.(*mheap).alloc(0xc73c60, 0x1dcd66, 0x7f6037010101, 0x4176b5)
>         /root/.gvm/gos/go1.11/src/runtime/mheap.go:758 +0x8a
> runtime.largeAlloc(0x3b9aca008, 0x450101, 0x7f603aee4000)
>         /root/.gvm/gos/go1.11/src/runtime/malloc.go:1019 +0x97
> runtime.mallocgc.func1()
>         /root/.gvm/gos/go1.11/src/runtime/malloc.go:914 +0x46
> runtime.systemstack(0x7fff28e832b0)
>         /root/.gvm/gos/go1.11/src/runtime/asm_amd64.s:351 +0x66
> runtime.mstart()
>         /root/.gvm/gos/go1.11/src/runtime/proc.go:1229
> 
> goroutine 1 [running]:
> runtime.systemstack_switch()
>         /root/.gvm/gos/go1.11/src/runtime/asm_amd64.s:311 fp=0xc0000c7920 sp=0xc0000c7918 pc=0x4561a0
> runtime.mallocgc(0x3b9aca008, 0x830440, 0x885f01, 0xc000140008)
>         /root/.gvm/gos/go1.11/src/runtime/malloc.go:913 +0x896 fp=0xc0000c79c0 sp=0xc0000c7920 pc=0x40d916
> runtime.makeslice(0x830440, 0x77359401, 0x77359401, 0x0, 0xc8b4e8, 0x0)
>         /root/.gvm/gos/go1.11/src/runtime/slice.go:70 +0x77 fp=0xc0000c79f0 sp=0xc0000c79c0 pc=0x441877
> github.com/pinterest/bender/hist.NewHistogram(...)
>         /root/.gvm/pkgsets/go1.11/global/src/github.com/pinterest/bender/hist/hist.go:40
> github.com/facebookincubator/fbender/cmd/core/runner.(*runner).Before(0xc0000902d0, 0x7d0, 0x85ce60, 0xc0000fa9a0, 0x30, 0xc00012e810)
>         /root/.gvm/pkgsets/go1.11/global/src/github.com/facebookincubator/fbender/cmd/core/runner/runner.go:77 +0x47f fp=0xc0000c7ad8 sp=0xc0000c79f0 pc=0x60bb5f
> github.com/facebookincubator/fbender/cmd/core/runner.(*ThroughputRunner).Before(0xc0000902d0, 0x7d0, 0x85ce60, 0xc0000fa9a0, 0xc0000fa9a0, 0x42add2)
>         /root/.gvm/pkgsets/go1.11/global/src/github.com/facebookincubator/fbender/cmd/core/runner/throughput.go:38 +0x58 fp=0xc0000c7b50 sp=0xc0000c7ad8 pc=0x60c018
> github.com/facebookincubator/fbender/tester/run.loadTestThroughput(0x951480, 0xc0000902d0, 0x94f400, 0xc00000c960, 0x85ce60, 0xc0000fa9a0, 0x7d0, 0x0, 0x0)
>         /root/.gvm/pkgsets/go1.11/global/src/github.com/facebookincubator/fbender/tester/run/throughput.go:68 +0xee fp=0xc0000c7bb0 sp=0xc0000c7b50 pc=0x60d76e
> github.com/facebookincubator/fbender/tester/run.LoadTestThroughputFixed(0x951480, 0xc0000902d0, 0x85ce60, 0xc0000fa9a0, 0xc0000235c0, 0x3, 0x4, 0x0, 0x0)
>         /root/.gvm/pkgsets/go1.11/global/src/github.com/facebookincubator/fbender/tester/run/throughput.go:28 +0x14b fp=0xc0000c7c20 sp=0xc0000c7bb0 pc=0x60d31b
> github.com/facebookincubator/fbender/cmd/core.fixedThroughputExecutor(0xc00000c980, 0xc0000fa9a0, 0xc00000c980, 0x0)
>         /root/.gvm/pkgsets/go1.11/global/src/github.com/facebookincubator/fbender/cmd/core/exec.go:75 +0x8e fp=0xc0000c7c78 sp=0xc0000c7c20 pc=0x612ace
> github.com/facebookincubator/fbender/cmd/core.exec.func1(0xc000121180, 0xc000097c20, 0x3, 0xa, 0x0, 0x0)
>         /root/.gvm/pkgsets/go1.11/global/src/github.com/facebookincubator/fbender/cmd/core/exec.go:39 +0xf4 fp=0xc0000c7d00 sp=0xc0000c7c78 pc=0x613e44
> github.com/spf13/cobra.(*Command).execute(0xc000121180, 0xc000097ae0, 0xa, 0xa, 0xc000121180, 0xc000097ae0)
>         /root/.gvm/pkgsets/go1.11/global/src/github.com/spf13/cobra/command.go:762 +0x473 fp=0xc0000c7df0 sp=0xc0000c7d00 pc=0x5a6663
> github.com/spf13/cobra.(*Command).ExecuteC(0xc68820, 0xc0000c7f88, 0x4073a0, 0xc00007a058)
>         /root/.gvm/pkgsets/go1.11/global/src/github.com/spf13/cobra/command.go:852 +0x2fd fp=0xc0000c7f30 sp=0xc0000c7df0 pc=0x5a705d
> github.com/spf13/cobra.(*Command).Execute(0xc68820, 0x0, 0x0)
>         /root/.gvm/pkgsets/go1.11/global/src/github.com/spf13/cobra/command.go:800 +0x2b fp=0xc0000c7f60 sp=0xc0000c7f30 pc=0x5a6d3b
> github.com/facebookincubator/fbender/cmd.Execute()
>         /root/.gvm/pkgsets/go1.11/global/src/github.com/facebookincubator/fbender/cmd/cmd.go:124 +0x2d fp=0xc0000c7f88 sp=0xc0000c7f60 pc=0x7e9c8d
> main.main()
>         /root/.gvm/pkgsets/go1.11/global/src/github.com/facebookincubator/fbender/main.go:16 +0x20 fp=0xc0000c7f98 sp=0xc0000c7f88 pc=0x7e9e80
> runtime.main()
>         /root/.gvm/gos/go1.11/src/runtime/proc.go:201 +0x207 fp=0xc0000c7fe0 sp=0xc0000c7f98 pc=0x42d9e7
> runtime.goexit()
>         /root/.gvm/gos/go1.11/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc0000c7fe8 sp=0xc0000c7fe0 pc=0x458281
> 
> goroutine 8 [runnable]:
> github.com/facebookincubator/fbender/utils.NewBackgroundSpinner.func1(0x8d8514, 0x12, 0x94e140, 0xc0000d6000, 0xc000122000, 0xc000084510, 0x5f5e100)
>         /root/.gvm/pkgsets/go1.11/global/src/github.com/facebookincubator/fbender/utils/spinner.go:37
> created by github.com/facebookincubator/fbender/utils.NewBackgroundSpinner
>         /root/.gvm/pkgsets/go1.11/global/src/github.com/facebookincubator/fbender/utils/spinner.go:37 +0x117

**Comment by earlgreyz** [comment]
Hey @sanguohot. Thank you for posting the issue. I've tested the query you've posted and everything seem to work for me.


```sh
❯ fbender http t f -t www.facebook.com -d 10s -s 10 -o /dev/null
GET /
Cleaning up the memory... Done.
Preparing the test... Done.
Running test: 10
   9s [====================================================================] 100 / 100 100%
Percentiles (1ms):
 Min:     239
 Median:  260
 90th:    471
 99th:    744
 99.9th:  1106
 99.99th: 1106
 Max:     1106
Stats:
 Average (1ms): 328.330000
 Total requests: 100
 Elapsed Time (sec): 10.2570
 Average QPS: 9.75
 Errors: 0
 Percent errors: 0.00
```

In the first one you had an empty line in an input which `fbender` was unable to parse:

```
Warning: Error parsing input line "": input must have a format of 'GET RelativeURL' or 'POST 
```


Regarding the second attempt it seems like your device ran out of memory.
```
fatal error: runtime: out of memory
```

Take a look at the [statistics](https://github.com/facebookincubator/fbender/blob/master/docs/USAGE.md#statistics) and [troubleshooting](https://github.com/facebookincubator/fbender/blob/master/docs/USAGE.md#out-of-memory) sections in the README file to learn how to decrease the memory usage.

**Comment by sanguohot** [comment]
@earlgreyz Sorry come back too late.
I can still not get it to work with the first case.
I just input `fbender http t f -t www.baidu.com -d 10s -s 10 -o /dev/null` , then press `ENTER`, type 'GET /' and press `ENTER` again, it give me the same error.
But it is very ok with the second one.
Also it would be nice to use `go mod and vendor` if possible.

**Comment by earlgreyz** [comment]
It tries to parse all lines you pass (including empty one after you pressed `ENTER`). This is just a warning. You should use `^D` to finish input to avoid it showing up.

```sh
fbender http t f -t www.baidu.com -d 10s -s 10 -o /dev/null
GET /<ENTER>
<^D>
```

I recommend creating an input file to avoid typing the input with every test:

```sh
fbender http t f -t www.baidu.com -d 10s -s 10 -o /dev/null -i myinput.txt
```

or you can use:

```sh
echo "GET /" | fbender http t f -t www.baidu.com -d 10s -s 10 -o /dev/null
```
