### ISSUE TITLE
Is there a way to test HTTP server which serving json request?

### ISSUE THREAD

**Issue by wangsikuan** [facebookincubator/fbender#11]
I found fbender only supports form data on HTTP protocol.

**Comment by lsiudut** [comment]
Hey @wangsikuan , can you clarify a bit what do you mean exactly?

If you're referring to HTTP POST data then only key=value / form-urlencoded is supported for now. It should be trivial enough to add json support and we can look into it though, but I can't tell when will it be ready.

Also feel free to submit PR if you wish to, we're happy to work on that with you :).

**Comment by pallotron** [comment]
well no response in 7d :(
closing. reopen when you see this. :)
