### ISSUE TITLE
Package github.com/mdlayher/eui64: no Go files in $GOPATH/src/github.com/mdlayher/eui64

### ISSUE THREAD

**Issue by advancedwebdeveloper** [facebookincubator/fbender#13]
Hello.
Wanted to inform you about such a bug.

I tried to
> $ go get -u github.com/facebookincubator/fbender
> package github.com/mdlayher/eui64: no Go files in /home/oceanfish81/go/src/github.com/mdlayher/eui64
> 
and
> $ go run main.go
> package command-line-arguments
> 	imports github.com/facebookincubator/fbender/cmd
> 	imports github.com/facebookincubator/fbender/cmd/dhcpv6
> 	imports github.com/facebookincubator/fbender/tester/dhcpv6
> 	imports github.com/pinterest/bender/dhcpv6
> 	imports github.com/mdlayher/eui64: no Go files in /home/oceanfish81/go/src/github.com/mdlayher/eui64

and in both cases - there is the very same bug.
 
I am using

> $ go version
> go version go1.15.2 gollvm LLVM 12.0.0git linux/amd64

and here is my env.:

> $ go env
> GO111MODULE=""
> GOARCH="amd64"
> GOBIN=""
> GOCACHE="/home/oceanfish81/.cache/go-build"
> GOENV="/home/oceanfish81/.config/go/env"
> GOEXE=""
> GOFLAGS=""
> GOHOSTARCH="amd64"
> GOHOSTOS="linux"
> GOINSECURE=""
> GOMODCACHE="/home/oceanfish81/go/pkg/mod"
> GONOPROXY=""
> GONOSUMDB=""
> GOOS="linux"
> GOPATH="/home/oceanfish81/go"
> GOPRIVATE=""
> GOPROXY="https://proxy.golang.org,direct"
> GOROOT="/home/oceanfish81/gollvm_dist"
> GOSUMDB="sum.golang.org"
> GOTMPDIR=""
> GOTOOLDIR="/home/oceanfish81/gollvm_dist/tools"
> GCCGO="/home/oceanfish81/gollvm_dist/bin/llvm-goc"
> AR="ar"
> CC="/usr/bin/clang"
> CXX="/usr/bin/clang++"
> CGO_ENABLED="1"
> GOMOD=""
> CGO_CFLAGS="-g -O2"
> CGO_CPPFLAGS=""
> CGO_CXXFLAGS="-g -O2"
> CGO_FFLAGS="-g -O2"
> CGO_LDFLAGS="-g -O2"
> PKG_CONFIG="pkg-config"
> GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build858050304=/tmp/go-build -gno-record-gcc-switches -funwind-tables"
>

**Comment by advancedwebdeveloper** [comment]
CC @mdlayher

**Comment by mdlayher** [comment]
You want https://godoc.org/github.com/mdlayher/netx/eui64 instead now.

**Comment by earlgreyz** [comment]
The package is never accessed directly in fbender it is imported as a dependency of [pinterest/bender](https://github.com/pinterest/bender). Preparing a PR, but there seems to be more outdated libraries there that need to be fixed. I will comment with the link to the PR later. As a quick fix, to test your before the changes are upstreamed you can symlink the library to its old name, i.e. in your `GO_HOME`

```sh
go get -u github.com/mdlayher/netx/eui64
ln -s github.com/mdlayher/netx/eui64 github.com/mdlayher/eui64
```

**Comment by earlgreyz** [comment]
Created a PR https://github.com/pinterest/bender/pull/41

**Comment by earlgreyz** [comment]
This has been merged therefore the issue can be closed.

**Comment by advancedwebdeveloper** [comment]
You didn't comment on a possibility of adding gollvm into your CI pipeline

**Comment by earlgreyz** [comment]
@advancedwebdeveloper could you create a separate issue for that? It would be very nice if you could also prepare a PR adding gollvm to the pipeline, I'm sure it will get accepted . There is `.travis.yml` file in the project root directory which controls CI. I'd be glad to help, but your PR will have to get approved by someone from FB to be merged.

**Comment by insomniacslk** [comment]
thank you @earlgreyz !
