### ISSUE TITLE
Is there a way to test Websocket connections?

### ISSUE THREAD

**Issue by mofirouz** [facebookincubator/fbender#2]
Hi. I work on the [Nakama](https://github.com/heroiclabs/nakama) project. I'd like to use this tool to benchmark Nakama (currently using a custom version of Tsung). Is there a way to use this tool to benchmark standard Websocket connections?

**Comment by earlgreyz** [comment]
Hi @mofirouz,
At the moment fbender doesn't support websockets. I've created a [high level guide](https://github.com/facebookincubator/fbender/blob/master/docs/EXTENDING.md) on how to add support for new protocol if you are interested in doing that (I can also help you with the process). There are ready to use Go libraries for websockets and the test itself should be similar to what we do in case of TFTP.

**Comment by mofirouz** [comment]
Hi @earlgreyz - Thanks for the hint. I'll have a look and will be in touch closer to the time that when I start to explore and implement this.
